require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::RightsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Right. As you add validations to Admin::Right, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::RightsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_rights as @admin_rights" do
      right = Admin::Right.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_rights).should eq([right])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_right as @admin_right" do
      right = Admin::Right.create! valid_attributes
      get :show, {:id => right.to_param}, valid_session
      assigns(:admin_right).should eq(right)
    end
  end

  describe "GET new" do
    it "assigns a new admin_right as @admin_right" do
      get :new, {}, valid_session
      assigns(:admin_right).should be_a_new(Admin::Right)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_right as @admin_right" do
      right = Admin::Right.create! valid_attributes
      get :edit, {:id => right.to_param}, valid_session
      assigns(:admin_right).should eq(right)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Right" do
        expect {
          post :create, {:admin_right => valid_attributes}, valid_session
        }.to change(Admin::Right, :count).by(1)
      end

      it "assigns a newly created admin_right as @admin_right" do
        post :create, {:admin_right => valid_attributes}, valid_session
        assigns(:admin_right).should be_a(Admin::Right)
        assigns(:admin_right).should be_persisted
      end

      it "redirects to the created admin_right" do
        post :create, {:admin_right => valid_attributes}, valid_session
        response.should redirect_to(Admin::Right.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_right as @admin_right" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Right.any_instance.stub(:save).and_return(false)
        post :create, {:admin_right => {}}, valid_session
        assigns(:admin_right).should be_a_new(Admin::Right)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Right.any_instance.stub(:save).and_return(false)
        post :create, {:admin_right => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_right" do
        right = Admin::Right.create! valid_attributes
        # Assuming there are no other admin_rights in the database, this
        # specifies that the Admin::Right created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Right.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => right.to_param, :admin_right => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested admin_right as @admin_right" do
        right = Admin::Right.create! valid_attributes
        put :update, {:id => right.to_param, :admin_right => valid_attributes}, valid_session
        assigns(:admin_right).should eq(right)
      end

      it "redirects to the admin_right" do
        right = Admin::Right.create! valid_attributes
        put :update, {:id => right.to_param, :admin_right => valid_attributes}, valid_session
        response.should redirect_to(right)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_right as @admin_right" do
        right = Admin::Right.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Right.any_instance.stub(:save).and_return(false)
        put :update, {:id => right.to_param, :admin_right => {}}, valid_session
        assigns(:admin_right).should eq(right)
      end

      it "re-renders the 'edit' template" do
        right = Admin::Right.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Right.any_instance.stub(:save).and_return(false)
        put :update, {:id => right.to_param, :admin_right => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_right" do
      right = Admin::Right.create! valid_attributes
      expect {
        delete :destroy, {:id => right.to_param}, valid_session
      }.to change(Admin::Right, :count).by(-1)
    end

    it "redirects to the admin_rights list" do
      right = Admin::Right.create! valid_attributes
      delete :destroy, {:id => right.to_param}, valid_session
      response.should redirect_to(admin_rights_url)
    end
  end

end
